### ISSUE TITLE
Detect framerate from original gif

### ISSUE THREAD

**Issue by goldenapples** [fusioneng/gif2html5-app#36]
Apologies for jumping in near the end of the project with a possibly dumb question here:

Why are you hardcoding the framerate to 15fps? That seems like something of a magic number, and might (from a totally naive perspective) explain some of the flickering you're describing in output.

It seems to me that [reading delay values from the original gif](http://stackoverflow.com/questions/13752717/how-do-i-use-imagemagick-to-determine-the-framerate-of-a-gif), calculating the greatest common factor, and then [converting that number to a frames per second value](http://stackoverflow.com/questions/14583330/ffmpeg-frame-rate-when-converting-from-gif-to-mp4) would be a more logical approach.

**Comment by danielbachhuber** [comment]
:+1: 

cc @noppanit @mpatek

**Comment by noppanit** [comment]
Oh I took it off already. Right now we're not doing that anymore. I did that just to test the short video clip.

**Comment by noppanit** [comment]
Sorry for the confusion.

**Comment by noppanit** [comment]
Closing in favor of. https://github.com/fusioneng/gif2html5-app/pull/35#partial-pull-merging
