### ISSUE TITLE
Convert to jpeg and compress instead of png.

### ISSUE THREAD

**Issue by noppanit** [fusioneng/gif2html5-app#46]
We need to convert our picture to jpg because png is too large. Also, we need to compress and cut up the images for responsive devices.

**Comment by danielbachhuber** [comment]
> Also, we need to compress and cut up the images for responsive devices.

Let's limit the scope of the change in gif2html5 to just converting to JPGs instead of PNGs. We can leave it up to the implementing application to make the images responsive.

**Comment by noppanit** [comment]
ok

**Comment by noppanit** [comment]
Closed as merged.
