### ISSUE TITLE
Upgrading to Python3

### ISSUE THREAD

**Issue by noppanit** [fusioneng/gif2html5-app#47]
@mpatek Do you think it's worth upgrading to Python3? Since all our python applications are Python3.

**Comment by mpatek** [comment]
Yes, I think it's probably worth it, especially if it doesn't involve much effort (and it often does not). You should check to see if the dependencies in `requirements.txt` work with Python3 (It might also be a good idea to make sure that everything in `requirements.txt` is still required). If all of our dependencies look good, then it might just be a matter of running [2to3](https://docs.python.org/2/library/2to3.html) on our code, making the required changes, and doing some testing in the staging environment.

**Comment by noppanit** [comment]
Closing as merged.
